// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurante.Repository.Data;

namespace Restaurante.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Restaurante.Domain.Consumo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("data");

                    b.Property<int?>("restauranteid");

                    b.Property<decimal>("valor");

                    b.HasKey("id");

                    b.HasIndex("restauranteid");

                    b.ToTable("Consumos");
                });

            modelBuilder.Entity("Restaurante.Domain.Restaurante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("bairro");

                    b.Property<string>("cidade");

                    b.Property<string>("endereco");

                    b.Property<string>("estado");

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("Restaurante.Domain.Consumo", b =>
                {
                    b.HasOne("Restaurante.Domain.Restaurante", "restaurante")
                        .WithMany()
                        .HasForeignKey("restauranteid");
                });
#pragma warning restore 612, 618
        }
    }
}
